# general
background = '#303446'
border_fg = '#51576d'
text_fg = '#c6d0f5'
dimmed_text_fg = '#737994'
# input
input_text_fg = '#eebebe'
result_count_fg = '#eebebe'
# results
result_name_fg = '#8caaee'
result_line_number_fg = '#e5c890'
result_value_fg = '#babbf1'
selection_bg = '#414559'
match_fg = '#a6d189'
# preview
preview_title_fg = '#eebebe'
# modes
channel_mode_fg = '#eebebe'
remote_control_mode_fg = '#a6d189'
send_to_channel_mode_fg = '#99d1db'

